POST http://localhost:3000/signup
Content-Type: application/json

{
    "email":"1@qq.com",
    "name":"Matt",
    "password":123456,
    "gender":1
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"1@qq.com",
    "password":123456
}

###
POST http://localhost:3000/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAcXEuY29tIiwicGFzc3dvcmQiOjEyMzQ1NiwiaWF0IjoxNjMzMDY2MTIwfQ.UBGc9oQpNXZbmvp1Ht-twCsDFnQtrutzcL25D1EhRko

###
POST http://localhost:3000/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAcXEuY29tIiwicGFzc3dvcmQiOjEyMzQ1NiwiaWF0IjoxNjMzMDY2MTIwfQ.UBGc9oQpNXZbmvp1Ht-twCsDFnQtrutzcL25D1EhRko
Content-Type: application/json

{
    "ownerId":{"$oid":"61569c7ea6801231e7796885"},
    "receiverId":{"$oid":"61569c7ea6801231e7796885"},
    "content":"I love you",
    "createdAt":{"$date": "2014-01-22T14:56:59.301Z"},
    "availableAt":"20211001" 
}