POST http://localhost:3000/signup
Content-Type: application/json

{
    "email":"1@qq.com",
    "name":"GF",
    "password":"123456",
    "gender":0
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"2@qq.com",
    "password":"123456"
}

###
POST http://localhost:3000/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAcXEuY29tIiwicGFzc3dvcmQiOjEyMzQ1NiwiaWF0IjoxNjMzMDY2MTIwfQ.UBGc9oQpNXZbmvp1Ht-twCsDFnQtrutzcL25D1EhRko

###
POST http://localhost:3000/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAcXEuY29tIiwicGFzc3dvcmQiOjEyMzQ1NiwiaWF0IjoxNjMzMjU5NzE4fQ.NrscTerfz7aSonhuCD01HNyc0uIumKeEsCw8Pwofd6M
Content-Type: application/json

{
    "ownerId":{"$oid":"61569c7ea6801231e7796885"},
    "receiverId":{"$oid":"61569c7ea6801231e7796885"},
    "content":"I love you too",
    "createdAt":{"$date": "2014-01-22T14:56:59.301Z"},
    "availableAt":"20211001" 
}

###
POST http://localhost:3000/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAcXEuY29tIiwicGFzc3dvcmQiOjEyMzQ1NiwiaWF0IjoxNjMzMjU5NzE4fQ.NrscTerfz7aSonhuCD01HNyc0uIumKeEsCw8Pwofd6M
Content-Type: application/json

{
    "receiverId":{"$oid":"61569c7ea6801231e7796885"},
    "time":"20211001" 
}

###
GET http://localhost:3000/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJAcXEuY29tIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpYXQiOjE2MzM2OTIzMzB9.S37JTguQd5ydkQRIwaDHEA3HoD5kkwVP_8Ba1XXVxpA

###
POST http://localhost:3000/create-request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAcXEuY29tIiwiX2lkIjoiNjE2MTI4YzMxMTMyMWQwNmUyYTIzZWEwIiwiaWF0IjoxNjMzNzU3NzIyfQ.wPKuYN2BkixiP_PwlTP61ucV_487N__PZt0Kf7JM_Bs
Content-Type: application/json

{
    "targetEmail":"2@qq.com"
}

###
GET http://localhost:3000/get-request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJAcXEuY29tIiwiX2lkIjoiNjE1ZWQ5OGNmYmM3MmM2NDNhNTg0NmMyIiwiaWF0IjoxNjMzNzU4OTkwfQ.fE9Vw1vpcMww6mEQpc0C0ZrL3Xv3bxYUPGKXy4KT89A

###
POST http://localhost:3000/approve-request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJAcXEuY29tIiwiX2lkIjoiNjE1ZWQ5OGNmYmM3MmM2NDNhNTg0NmMyIiwiaWF0IjoxNjMzNzU4OTkwfQ.fE9Vw1vpcMww6mEQpc0C0ZrL3Xv3bxYUPGKXy4KT89A
Content-Type: application/json

{
    "_id":{"$oid":"61613683bcf587a977a59f07"}
}

###
GET http://localhost:3000/remove-mate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJAcXEuY29tIiwiX2lkIjoiNjE1ZWQ5OGNmYmM3MmM2NDNhNTg0NmMyIiwiaWF0IjoxNjMzNzU4OTkwfQ.fE9Vw1vpcMww6mEQpc0C0ZrL3Xv3bxYUPGKXy4KT89A
