POST http://localhost:3000/signup
Content-Type: application/json

{
    "email":"mattgxt@gmail.com",
    "name":"test",
    "password":"matt1234",
    "gender":0
}

###
GET http://localhost:3000/verify?code=d3144f8bcdee43f2e9f0e84c78caf2da413bd3c8

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"mattgxt@gmail.com",
    "password":"matt1234"
}

###
POST http://localhost:3000/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRpYW55aXhpbmdjaGVuQGdtYWlsLmNvbSIsIl9pZCI6IjYxNjU2N2Y2YTk4NDk3NGNlNDlmNzFjMCIsImlhdCI6MTYzNDAzNTc2NH0.bVxMD1A5m_oU2IUxfMrKeGvrqGsAnerhhp4SP7cFxgE

###
POST http://localhost:3000/create-capsule
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJAcXEuY29tIiwiX2lkIjoiNjE1ZWQ5OGNmYmM3MmM2NDNhNTg0NmMyIiwiaWF0IjoxNjMzODQ1ODY5fQ.jlfjECEH_E2jURwnGOKrZjUm2wZLRGCZ8TtIOjiM8Iw
Content-Type: application/json

{
    "content":"I love you too",
    "availableAt":0
}

###
POST http://localhost:3000/get-capsule
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAcXEuY29tIiwicGFzc3dvcmQiOjEyMzQ1NiwiaWF0IjoxNjMzMjU5NzE4fQ.NrscTerfz7aSonhuCD01HNyc0uIumKeEsCw8Pwofd6M
Content-Type: application/json

{
    "receiverId":{"$oid":"61569c7ea6801231e7796885"},
    "time":"20211001" 
}

###
GET http://localhost:3000/check
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRpYW55aXhpbmdjaGVuQGdtYWlsLmNvbSIsIl9pZCI6IjYxNjU2N2Y2YTk4NDk3NGNlNDlmNzFjMCIsImlhdCI6MTYzNDAzNTc2NH0.bVxMD1A5m_oU2IUxfMrKeGvrqGsAnerhhp4SP7cFxgE

###
POST http://localhost:3000/create-request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRpYW55aXhpbmdjaGVuQGdtYWlsLmNvbSIsIl9pZCI6IjYxNjU2N2Y2YTk4NDk3NGNlNDlmNzFjMCIsImlhdCI6MTYzNDAzNTkzM30.PX-UUsjzigHvUfnjgfHkSh2GuYj9S7SZEOFbBedx4yk
Content-Type: application/json

{
    "targetEmail":"mattgxt@gmail.com"
}

###
GET http://localhost:3000/get-request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJAcXEuY29tIiwiX2lkIjoiNjE1ZWQ5OGNmYmM3MmM2NDNhNTg0NmMyIiwiaWF0IjoxNjMzNzU4OTkwfQ.fE9Vw1vpcMww6mEQpc0C0ZrL3Xv3bxYUPGKXy4KT89A

###
POST http://localhost:3000/approve-request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJAcXEuY29tIiwiX2lkIjoiNjE1ZWQ5OGNmYmM3MmM2NDNhNTg0NmMyIiwiaWF0IjoxNjMzNzU4OTkwfQ.fE9Vw1vpcMww6mEQpc0C0ZrL3Xv3bxYUPGKXy4KT89A
Content-Type: application/json

{
    "_id":{"$oid":"616568e8216e246af17009cf"}
}

###
GET http://localhost:3000/remove-mate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJAcXEuY29tIiwiX2lkIjoiNjE1ZWQ5OGNmYmM3MmM2NDNhNTg0NmMyIiwiaWF0IjoxNjMzNzU4OTkwfQ.fE9Vw1vpcMww6mEQpc0C0ZrL3Xv3bxYUPGKXy4KT89A
